inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - strictest.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/SymbolArray:
  EnforcedStyle: brackets

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
